const examples = {
  JavaScript: [
    [
      "const sum = (...nums) => nums.reduce((a, b) => a + b, 0);",
      "const obj = { name: 'Alice', greet: () => `Hi, ${obj.name}!` };",
      "async function fetchData(url) { try { return await fetch(url); } }",
      "const formatted = arr.map((v, i) => `[${i}]: ${v ?? 'N/A'}`);",
      "let count = 0; while (count++ < 5) { console.log(`Step: ${count}`); }",
    ],
    [
      "const greet = (name) => { console.log(`Hello, ${name}!`); };",
      `for (let i = 0; i < arr.length; i++) { sum += arr[i] ?? 0; }`,
      "const user = { isAdmin: true, getInfo: () => `${this.isAdmin}` };",
      `if (typeof input === 'string') { return input.toUpperCase(); }`,
      `try { JSON.parse(data); } catch (e) { console.error(e.message); }`,
    ],
    [
      `function greetUser() {`,
      `  const name = prompt("What's your name?");`,
      `  if (name) {`,
      "    alert(`Welcome, ${name}!`);",
      "    console.log(`User greeted: ${name}`);",
      `  } else {`,
      `    alert("No name provided!");`,
      `    console.log("No name was entered.");`,
      `  }`,
      `}`,
    ],
  ],
  Python: [
    [
      `print("Hello, Python!")`,
      `name, age = "Alice", 25`,
      `for i in range(10): print(i, end=" ")`,
      `if x == 42: print("The answer is 42")`,
      `numbers = [1, 2, 3, 4, 5]`,
      `def greet(name): return f"Hello, {name}!"`,
      `data = {"name": "Alice", "age": 30}`,
      `import math; print(math.pi)`,
      `print("Sum:", sum([1, 2, 3]))`,
      `while count > 0: count -= 1`,
    ],
    [
      `def main():`,
      `  print("Welcome to the number adder!")`,
      `  nums = input("Enter numbers separated by spaces: ")`,
      `  num_list = [int(n) for n in nums.split()]`,
      `  total = sum(num_list)`,
      `  print(f"You entered: {num_list}")`,
      `  print(f"The total sum is: {total}")`,
      `  return True`,
      `if __name__ == "__main__":`,
      `  main()`,
    ],
  ],
  JAVA: [
    [
      `System.out.println("Hello, Java!");`,
      `int num = 42; String text = "Java is cool!";`,
      `for (int i = 0; i < 10; i++) { System.out.print(i + " "); }`,
      `if (age >= 18) { System.out.println("Adult"); }`,
      `String[] names = {"Alice", "Bob", "Charlie"};`,
      `while (count > 0) { count--; }`,
      `class Person { String name; int age; }`,
      `File file = new File("data.txt");`,
      `System.out.printf("Formatted number: %.2f", value);`,
      `@Override public void run() { System.out.println("Running"); }`,
    ],
    [
      `import java.util.Scanner;`,
      `public class Welcome {`,
      `  public static void main(String[] args) {`,
      `    Scanner scanner = new Scanner(System.in);`,
      `    System.out.print("Enter your name: ");`,
      `    String name = scanner.nextLine();`,
      `    System.out.println("Welcome, " + name + "!");`,
      `    scanner.close();`,
      `  }`,
      `}`,
    ],
  ],
  HTML: [
    [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head><title>My Web Page</title></head>`,
      `<a href="https://example.com">Click Here</a>`,
      `<button onclick="alert('Hello!')">Click Me</button>`,
      `<input type="text" placeholder="Enter your name">`,
      `<img src="image.jpg" alt="Sample Image">`,
      `<script>alert("Hello, JavaScript!");</script>`,
      `<form action="submit.php" method="POST">`,
      `<link rel="stylesheet" href="./css/global.css" />`,
    ],
    [
      `<!DOCTYPE html>`,
      `<html>`,
      `<head><title>Welcome</title></head>`,
      `<body>`,
      `  <h1>Hi there!</h1>`,
      `  <p>Welcome to Getta webpage.</p>`,
      `  <input type="text" id="name" placeholder="Polytech~">`,
      `  <button onclick="alert('Hi, '+name.value)">Greet</button>`,
      `</body>`,
      `</html>`,
    ],
  ],
};

window.examples = examples;
