const examples = {
  JavaScript: [
    [
      `example....`,
      `example1....`,
      `example2....`,
      `example3....`,
      `example4....`,
      `example5....`,
      `example6....`,
      `example7....`,
      `example8....`,
      `example9....`,
    ],
    [
      `test....`,
      `test1....`,
      `test2....`,
      `test3....`,
      `test4....`,
      `test5....`,
      `test6....`,
      `test7....`,
      `test8....`,
      `test9....`,
    ],
  ],
  Python: [
    [
      `print("Hello, Python!")`,
      `name = "Alice"; age = 25`,
      `for i in range(10): print(i, end=" ")`,
      `if x == 42: print("The answer is 42")`,
      `numbers = [1, 2, 3, 4, 5]`,
      `def greet(name): return f"Hello, {name}!"`,
      `data = {"name": "Alice", "age": 30}`,
      `import math; print(math.pi)`,
      `print("Sum:", sum([1, 2, 3]))`,
      `while count > 0: count -= 1`,
    ],
    [
      `예시2`,
      `name = "Alice"; age = 25`,
      `for i in range(10): print(i, end=" ")`,
      `if x == 42: print("The answer is 42")`,
      `numbers = [1, 2, 3, 4, 5]`,
      `def greet(name): return f"Hello, {name}!"`,
      `data = {"name": "Alice", "age": 30}`,
      `import math; print(math.pi)`,
      `print("Sum:", sum([1, 2, 3]))`,
      `while count > 0: count -= 1`,
    ],
  ],
  JAVA: [
    [
      `System.out.println("Hello, Java!");`,
      `int num = 42; String text = "Java is cool!";`,
      `for (int i = 0; i < 10; i++) { System.out.print(i + " "); }`,
      `if (age >= 18) { System.out.println("Adult"); }`,
      `String[] names = {"Alice", "Bob", "Charlie"};`,
      `while (count > 0) { count--; }`,
      `class Person { String name; int age; }`,
      `File file = new File("data.txt");`,
      `System.out.printf("Formatted number: %.2f", value);`,
      `@Override public void run() { System.out.println("Running"); }`,
    ],
    [
      `예시2`,
      `int num = 42; String text = "Java is cool!";`,
      `for (int i = 0; i < 10; i++) { System.out.print(i + " "); }`,
      `if (age >= 18) { System.out.println("Adult"); }`,
      `String[] names = {"Alice", "Bob", "Charlie"};`,
      `while (count > 0) { count--; }`,
      `class Person { String name; int age; }`,
      `File file = new File("data.txt");`,
      `System.out.printf("Formatted number: %.2f", value);`,
      `@Override public void run() { System.out.println("Running"); }`,
    ],
  ],
  HTML: [
    [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head><title>My Web Page</title></head>`,
      `<a href="https://example.com">Click Here</a>`,
      `<button onclick="alert('Hello!')">Click Me</button>`,
      `<input type="text" placeholder="Enter your name">`,
      `<img src="image.jpg" alt="Sample Image">`,
      `<script>alert("Hello, JavaScript!");</script>`,
      `<form action="submit.php" method="POST">`,
      `<link rel="stylesheet" href="./css/global.css" />`,
    ],
    [
      `예시2`,
      `<html lang="en">`,
      `<head><title>My Web Page</title></head>`,
      `<a href="https://example.com">Click Here</a>`,
      `<button onclick="alert('Hello!')">Click Me</button>`,
      `<input type="text" placeholder="Enter your name">`,
      `<img src="image.jpg" alt="Sample Image">`,
      `<script>alert("Hello, JavaScript!");</script>`,
      `<form action="submit.php" method="POST">`,
      `<link rel="stylesheet" href="./css/global.css" />`,
    ],
  ],
};

window.examples = examples;
